version: '3.1'
services:
  nginx:
    image: rlkamradt/javaman-client
    restart: always
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ../..:/etc/certs
    ports:
     - "443:443"
  app:
    image: rlkamradt/javaman
    ports:
      - 3001:3001
